// ============================================================================
// Beispieldaten. In der echten App stammen Angebote aus KI-Prospekt-Import
// (Stufe 2) oder manueller Pflege.
// ============================================================================

const MAERKTE = [
  { id: "aldi",  name: "Aldi Süd", kurz: "AL", farbe: "#00457c", adresse: "Hauptstr. 12", entfernungKm: 0.6 },
  { id: "rewe",  name: "Rewe",     kurz: "RE", farbe: "#cc0000", adresse: "Marktplatz 3",  entfernungKm: 1.2 },
  { id: "lidl",  name: "Lidl",     kurz: "LI", farbe: "#0050aa", adresse: "Bahnhofstr. 8",  entfernungKm: 1.9 },
  { id: "edeka", name: "Edeka",    kurz: "ED", farbe: "#f9c100", entfernungKm: 2.8, adresse: "Ringstr. 21" },
  { id: "penny", name: "Penny",    kurz: "PE", farbe: "#e2001a", entfernungKm: 3.4, adresse: "Feldweg 5" },
];

// Hilfsfunktion hält die Rezeptdefinitionen kompakt & einheitlich.
function rez(o) {
  return {
    beliebt: false, budget: false, saison: ["ganzjährig"], diaet: [], rating: 4.5, bewertungen: 200,
    schwierigkeit: "einfach", ...o,
  };
}

const REZEPTE = [
  // --- Klassiker & Pasta ---------------------------------------------------
  rez({ id: "bolognese", name: "Spaghetti Bolognese", portionen: 2, dauerMin: 30, emoji: "🍝", veggie: false,
    kategorie: "Klassiker", kcal: 620, farbe: "#d2552b", beliebt: true, budget: true, rating: 4.8, bewertungen: 2143,
    diaet: ["high-protein"], beschreibung: "Der italienische Klassiker: kräftige Hackfleisch-Tomatensauce auf Spaghetti.",
    schritte: ["Zwiebeln & Knoblauch anbraten.", "Hackfleisch krümelig braten.", "Mit Tomaten ablöschen, 15 Min köcheln.", "Mit Spaghetti & Parmesan servieren."],
    zutaten: [
      { name: "Hackfleisch", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Spaghetti", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Zwiebeln", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Knoblauch", menge: 2, einheit: "Zehen", kategorie: "gemuese" },
      { name: "Parmesan", menge: 100, einheit: "g", kategorie: "kaese" }]}),
  rez({ id: "carbonara", name: "Spaghetti Carbonara", portionen: 2, dauerMin: 20, emoji: "🥓", veggie: false,
    kategorie: "Pasta", kcal: 650, farbe: "#a16207", beliebt: true, rating: 4.7, bewertungen: 1654, diaet: ["high-protein"],
    beschreibung: "Cremige Carbonara mit Ei & Parmesan – ohne Sahne, wie das Original.",
    schritte: ["Spaghetti kochen.", "Speck knusprig braten.", "Eier mit Parmesan verquirlen.", "Heiße Pasta mit Speck & Ei-Mix schwenken."],
    zutaten: [
      { name: "Spaghetti", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Eier", menge: 4, einheit: "Stk", kategorie: "eier" },
      { name: "Parmesan", menge: 80, einheit: "g", kategorie: "kaese" },
      { name: "Speck", menge: 150, einheit: "g", kategorie: "fleisch" }]}),
  rez({ id: "pasta_pesto", name: "Pasta mit Pesto", portionen: 2, dauerMin: 15, emoji: "🌿", veggie: true,
    kategorie: "Pasta", kcal: 560, farbe: "#15803d", beliebt: true, budget: true, rating: 4.6, bewertungen: 1209, diaet: ["vegetarisch"],
    beschreibung: "Blitzschnelle Pasta mit Pesto – das Last-Minute-Lieblingsgericht.",
    schritte: ["Spaghetti kochen.", "Nudelwasser auffangen.", "Mit Pesto & Wasser mischen, Parmesan darüber."],
    zutaten: [
      { name: "Spaghetti", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Pesto", menge: 190, einheit: "g", kategorie: "konserven" },
      { name: "Parmesan", menge: 80, einheit: "g", kategorie: "kaese" }]}),
  rez({ id: "nudeln_tomate", name: "Nudeln mit Tomatensauce", portionen: 2, dauerMin: 15, emoji: "🍅", veggie: true,
    kategorie: "Pasta", kcal: 480, farbe: "#dc2626", budget: true, rating: 4.4, bewertungen: 612, diaet: ["vegetarisch", "vegan"],
    beschreibung: "Schnelle, günstige Tomatensauce – immer ein sicherer Treffer.",
    schritte: ["Zwiebel & Knoblauch anbraten.", "Tomaten zugeben, würzen, köcheln.", "Mit Nudeln servieren."],
    zutaten: [
      { name: "Spaghetti", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Knoblauch", menge: 2, einheit: "Zehen", kategorie: "gemuese" }]}),
  rez({ id: "thunfisch_pasta", name: "Thunfisch-Pasta", portionen: 2, dauerMin: 20, emoji: "🐟", veggie: false,
    kategorie: "Pasta", kcal: 540, farbe: "#0e7490", budget: true, rating: 4.3, bewertungen: 388, diaet: ["high-protein"],
    beschreibung: "Proteinreiche Pasta mit Thunfisch und Tomaten – günstig & sättigend.",
    schritte: ["Nudeln kochen.", "Thunfisch mit Tomaten & Zwiebel erhitzen.", "Vermengen und würzen."],
    zutaten: [
      { name: "Spaghetti", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Thunfisch", menge: 240, einheit: "g", kategorie: "konserven" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "lasagne", name: "Lasagne", portionen: 4, dauerMin: 60, emoji: "🍲", veggie: false, schwierigkeit: "mittel",
    kategorie: "Klassiker", kcal: 720, farbe: "#b91c1c", beliebt: true, rating: 4.8, bewertungen: 1987, diaet: ["high-protein"],
    beschreibung: "Schichtweise Genuss: Hackfleischsauce, Béchamel und Käse.",
    schritte: ["Bolognese-Sauce kochen.", "Mit Platten & Béchamel schichten.", "Mit Käse 35 Min überbacken."],
    zutaten: [
      { name: "Hackfleisch", menge: 500, einheit: "g", kategorie: "fleisch" },
      { name: "Tomaten (Dose)", menge: 800, einheit: "g", kategorie: "konserven" },
      { name: "Käse", menge: 200, einheit: "g", kategorie: "kaese" },
      { name: "Milch", menge: 500, einheit: "ml", kategorie: "milch" },
      { name: "Zwiebeln", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "kaesespaetzle", name: "Käsespätzle", portionen: 2, dauerMin: 25, emoji: "🧀", veggie: true,
    kategorie: "Klassiker", kcal: 690, farbe: "#ca8a04", beliebt: true, rating: 4.7, bewertungen: 1342, diaet: ["vegetarisch"],
    beschreibung: "Herzhafte Spätzle mit viel Käse und Röstzwiebeln.",
    schritte: ["Spätzle erhitzen.", "Schichtweise mit Käse mischen.", "Mit gebratenen Zwiebeln toppen."],
    zutaten: [
      { name: "Spätzle", menge: 500, einheit: "g", kategorie: "nudeln" },
      { name: "Käse", menge: 200, einheit: "g", kategorie: "kaese" },
      { name: "Zwiebeln", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "risotto", name: "Pilzrisotto", portionen: 2, dauerMin: 35, emoji: "🍚", veggie: true, schwierigkeit: "mittel",
    kategorie: "Klassiker", kcal: 520, farbe: "#92766a", rating: 4.5, bewertungen: 498, diaet: ["vegetarisch"],
    beschreibung: "Cremiges Risotto mit Champignons und Parmesan.",
    schritte: ["Zwiebel anschwitzen, Reis zugeben.", "Nach und nach Brühe einrühren.", "Pilze & Parmesan unterheben."],
    zutaten: [
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" },
      { name: "Champignons", menge: 400, einheit: "g", kategorie: "gemuese" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Parmesan", menge: 80, einheit: "g", kategorie: "kaese" }]}),
  rez({ id: "gulasch", name: "Rindergulasch", portionen: 4, dauerMin: 90, emoji: "🥘", veggie: false, schwierigkeit: "mittel",
    kategorie: "Klassiker", kcal: 560, farbe: "#7c2d12", saison: ["Herbst", "Winter"], rating: 4.7, bewertungen: 743, diaet: ["high-protein", "low-carb"],
    beschreibung: "Zartes Gulasch, lange geschmort – Soulfood pur.",
    schritte: ["Fleisch scharf anbraten.", "Zwiebeln & Paprika zugeben.", "Mit Brühe 75 Min schmoren."],
    zutaten: [
      { name: "Rindergulasch", menge: 600, einheit: "g", kategorie: "fleisch" },
      { name: "Zwiebeln", menge: 3, einheit: "Stk", kategorie: "gemuese" },
      { name: "Paprika", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),

  // --- Familie / beliebt ---------------------------------------------------
  rez({ id: "haehnchen", name: "Hähnchen mit Brokkoli & Reis", portionen: 2, dauerMin: 35, emoji: "🍗", veggie: false,
    kategorie: "Familie", kcal: 540, farbe: "#c2410c", rating: 4.5, bewertungen: 654, diaet: ["high-protein", "low-carb"],
    beschreibung: "Saftige Hähnchenbrust mit knackigem Brokkoli und Reis.",
    schritte: ["Reis kochen.", "Hähnchen goldbraun braten.", "Brokkoli dämpfen, anrichten."],
    zutaten: [
      { name: "Hähnchenbrust", menge: 600, einheit: "g", kategorie: "fleisch" },
      { name: "Brokkoli", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" }]}),
  rez({ id: "wraps", name: "Hähnchen-Wraps", portionen: 2, dauerMin: 25, emoji: "🌯", veggie: false,
    kategorie: "Familie", kcal: 510, farbe: "#ca8a04", rating: 4.4, bewertungen: 398, diaet: ["high-protein"],
    beschreibung: "Knusprige Wraps mit Hähnchen und frischem Gemüse.",
    schritte: ["Hähnchen in Streifen braten.", "Gemüse schneiden.", "Tortillas füllen & rollen."],
    zutaten: [
      { name: "Hähnchenbrust", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Tortillas", menge: 6, einheit: "Stk", kategorie: "backen" },
      { name: "Paprika", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Tomaten", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "pizza", name: "Pizza Margherita", portionen: 2, dauerMin: 30, emoji: "🍕", veggie: true,
    kategorie: "Familie", kcal: 680, farbe: "#dc2626", beliebt: true, rating: 4.8, bewertungen: 2310, diaet: ["vegetarisch"],
    beschreibung: "Selbstgemachte Pizza mit Tomatensauce und Mozzarella.",
    schritte: ["Teig ausrollen.", "Mit Tomaten & Mozzarella belegen.", "Heiß backen, mit Basilikum servieren."],
    zutaten: [
      { name: "Pizzateig", menge: 400, einheit: "g", kategorie: "backen" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Mozzarella", menge: 250, einheit: "g", kategorie: "kaese" }]}),
  rez({ id: "burger", name: "Cheeseburger", portionen: 2, dauerMin: 25, emoji: "🍔", veggie: false,
    kategorie: "Familie", kcal: 720, farbe: "#b45309", beliebt: true, rating: 4.6, bewertungen: 1456, diaet: ["high-protein"],
    beschreibung: "Saftiger Burger mit selbstgeformtem Patty und Käse.",
    schritte: ["Patties formen & braten.", "Käse aufschmelzen.", "Buns mit Salat & Tomate belegen."],
    zutaten: [
      { name: "Hackfleisch", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Brot", menge: 2, einheit: "Stk", kategorie: "backen" },
      { name: "Käse", menge: 100, einheit: "g", kategorie: "kaese" },
      { name: "Tomaten", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "haehnchen_bowl", name: "Hähnchen-Reis-Bowl", portionen: 2, dauerMin: 25, emoji: "🥣", veggie: false,
    kategorie: "Familie", kcal: 560, farbe: "#16a34a", rating: 4.6, bewertungen: 567, diaet: ["high-protein"],
    beschreibung: "Bunte Bowl mit Hähnchen, Reis und viel Gemüse – meal-prep-tauglich.",
    schritte: ["Reis kochen.", "Hähnchen würzen & braten.", "Mit Gemüse in Schüsseln anrichten."],
    zutaten: [
      { name: "Hähnchenbrust", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" },
      { name: "Paprika", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Brokkoli", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),

  // --- Vegetarisch & Vegan -------------------------------------------------
  rez({ id: "curry", name: "Gemüse-Kokos-Curry", portionen: 2, dauerMin: 25, emoji: "🍛", veggie: true,
    kategorie: "Vegetarisch", kcal: 480, farbe: "#e0a416", rating: 4.6, bewertungen: 876, diaet: ["vegetarisch", "vegan"],
    beschreibung: "Cremiges Curry mit Kokosmilch und buntem Gemüse.",
    schritte: ["Reis aufsetzen.", "Gemüse anbraten, Currypaste rösten.", "Mit Kokosmilch köcheln."],
    zutaten: [
      { name: "Kokosmilch", menge: 400, einheit: "ml", kategorie: "konserven" },
      { name: "Paprika", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" },
      { name: "Currypaste", menge: 50, einheit: "g", kategorie: "gewuerze" }]}),
  rez({ id: "chili", name: "Chili sin Carne", portionen: 3, dauerMin: 30, emoji: "🌶️", veggie: true,
    kategorie: "Vegetarisch", kcal: 450, farbe: "#b91c1c", budget: true, rating: 4.6, bewertungen: 765, diaet: ["vegetarisch", "vegan", "high-protein"],
    beschreibung: "Würziger veganer Eintopf mit Bohnen und Mais.",
    schritte: ["Zwiebeln & Paprika anbraten.", "Tomaten, Bohnen, Mais zugeben.", "20 Min köcheln, mit Reis servieren."],
    zutaten: [
      { name: "Kidneybohnen", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Mais", menge: 300, einheit: "g", kategorie: "konserven" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Paprika", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" }]}),
  rez({ id: "linsen_dal", name: "Rote Linsen-Dal", portionen: 3, dauerMin: 30, emoji: "🍲", veggie: true,
    kategorie: "Vegetarisch", kcal: 420, farbe: "#ea580c", budget: true, rating: 4.7, bewertungen: 612, diaet: ["vegetarisch", "vegan", "high-protein"],
    beschreibung: "Wärmendes indisches Dal aus roten Linsen – proteinreich & vegan.",
    schritte: ["Zwiebel & Currypaste anbraten.", "Linsen mit Kokosmilch & Wasser kochen.", "20 Min köcheln, würzen."],
    zutaten: [
      { name: "Rote Linsen", menge: 300, einheit: "g", kategorie: "huelsenfruechte" },
      { name: "Kokosmilch", menge: 400, einheit: "ml", kategorie: "konserven" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Currypaste", menge: 40, einheit: "g", kategorie: "gewuerze" }]}),
  rez({ id: "kichererbsen_curry", name: "Kichererbsen-Curry", portionen: 3, dauerMin: 25, emoji: "🫛", veggie: true,
    kategorie: "Vegetarisch", kcal: 460, farbe: "#d97706", budget: true, rating: 4.5, bewertungen: 487, diaet: ["vegetarisch", "vegan", "high-protein"],
    beschreibung: "Sättigendes veganes Curry mit Kichererbsen und Tomaten.",
    schritte: ["Zwiebel anbraten.", "Kichererbsen, Tomaten & Kokosmilch zugeben.", "Köcheln und mit Reis servieren."],
    zutaten: [
      { name: "Kichererbsen", menge: 400, einheit: "g", kategorie: "huelsenfruechte" },
      { name: "Tomaten (Dose)", menge: 400, einheit: "g", kategorie: "konserven" },
      { name: "Kokosmilch", menge: 400, einheit: "ml", kategorie: "konserven" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" }]}),
  rez({ id: "tofu_pfanne", name: "Tofu-Gemüse-Pfanne", portionen: 2, dauerMin: 20, emoji: "🍳", veggie: true,
    kategorie: "Vegetarisch", kcal: 390, farbe: "#65a30d", rating: 4.3, bewertungen: 276, diaet: ["vegetarisch", "vegan", "high-protein", "low-carb"],
    beschreibung: "Knusprige Tofu-Pfanne mit buntem Gemüse – schnell & vegan.",
    schritte: ["Tofu würfeln & knusprig braten.", "Gemüse zugeben.", "Mit Sojasauce abschmecken."],
    zutaten: [
      { name: "Tofu", menge: 400, einheit: "g", kategorie: "tofu" },
      { name: "Paprika", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Brokkoli", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "gemuesepfanne", name: "Bunte Gemüsepfanne", portionen: 2, dauerMin: 20, emoji: "🥘", veggie: true,
    kategorie: "Vegetarisch", kcal: 410, farbe: "#059669", rating: 4.3, bewertungen: 213, diaet: ["vegetarisch", "vegan", "low-carb"],
    beschreibung: "Schnelle Pfanne mit Paprika, Brokkoli und Reis.",
    schritte: ["Reis kochen.", "Gemüse scharf anbraten.", "Mischen & würzen."],
    zutaten: [
      { name: "Paprika", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Brokkoli", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" }]}),
  rez({ id: "kartoffelsuppe", name: "Deftige Kartoffelsuppe", portionen: 3, dauerMin: 35, emoji: "🥔", veggie: true,
    kategorie: "Vegetarisch", kcal: 380, farbe: "#b45309", budget: true, saison: ["Herbst", "Winter"], rating: 4.5, bewertungen: 287, diaet: ["vegetarisch", "vegan"],
    beschreibung: "Wärmende Kartoffelsuppe – Soulfood für kalte Tage.",
    schritte: ["Kartoffeln & Zwiebeln würfeln.", "Andünsten, mit Brühe aufgießen.", "Weich kochen & pürieren."],
    zutaten: [
      { name: "Kartoffeln", menge: 800, einheit: "g", kategorie: "gemuese" },
      { name: "Zwiebeln", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Knoblauch", menge: 1, einheit: "Zehen", kategorie: "gemuese" }]}),
  rez({ id: "milchreis", name: "Cremiger Milchreis", portionen: 2, dauerMin: 30, emoji: "🍮", veggie: true,
    kategorie: "Frühstück", kcal: 430, farbe: "#e879a6", budget: true, rating: 4.6, bewertungen: 654, diaet: ["vegetarisch"],
    beschreibung: "Süßer Milchreis mit Zimt und Zucker – Kindheitsklassiker.",
    schritte: ["Reis in Milch quellen lassen.", "25 Min sanft köcheln.", "Mit Zimt & Zucker servieren."],
    zutaten: [
      { name: "Reis", menge: 250, einheit: "g", kategorie: "reis" },
      { name: "Milch", menge: 1000, einheit: "ml", kategorie: "milch" }]}),

  // --- Keto / Low Carb -----------------------------------------------------
  rez({ id: "zoodles", name: "Zucchini-Nudeln mit Pesto", portionen: 2, dauerMin: 15, emoji: "🥒", veggie: true,
    kategorie: "Vegetarisch", kcal: 320, farbe: "#16a34a", rating: 4.4, bewertungen: 412, diaet: ["vegetarisch", "keto", "low-carb"],
    beschreibung: "Leichte Low-Carb-Alternative: Zucchini-Spaghetti mit Pesto.",
    schritte: ["Zucchini in Streifen hobeln.", "Kurz anbraten.", "Mit Pesto & Parmesan mischen."],
    zutaten: [
      { name: "Zucchini", menge: 500, einheit: "g", kategorie: "gemuese" },
      { name: "Pesto", menge: 190, einheit: "g", kategorie: "konserven" },
      { name: "Parmesan", menge: 80, einheit: "g", kategorie: "kaese" }]}),
  rez({ id: "steak_brokkoli", name: "Steak mit Brokkoli", portionen: 2, dauerMin: 20, emoji: "🥩", veggie: false,
    kategorie: "Fleisch", kcal: 520, farbe: "#7f1d1d", rating: 4.7, bewertungen: 389, diaet: ["keto", "low-carb", "high-protein"],
    beschreibung: "Saftiges Steak mit Brokkoli – proteinreich und keto-tauglich.",
    schritte: ["Steak scharf anbraten, ruhen lassen.", "Brokkoli dämpfen.", "Mit Butter & Salz servieren."],
    zutaten: [
      { name: "Rindersteak", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Brokkoli", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "lachs_spinat", name: "Lachs auf Blattspinat", portionen: 2, dauerMin: 20, emoji: "🐟", veggie: false,
    kategorie: "Fisch", kcal: 480, farbe: "#0891b2", rating: 4.6, bewertungen: 421, diaet: ["keto", "low-carb", "high-protein"],
    beschreibung: "Gebratener Lachs auf cremigem Spinat – schnell & keto.",
    schritte: ["Lachs auf der Haut braten.", "Spinat mit Knoblauch dünsten.", "Zusammen anrichten."],
    zutaten: [
      { name: "Lachsfilet", menge: 300, einheit: "g", kategorie: "fisch" },
      { name: "Spinat", menge: 400, einheit: "g", kategorie: "gemuese" },
      { name: "Knoblauch", menge: 2, einheit: "Zehen", kategorie: "gemuese" }]}),
  rez({ id: "avocado_ei", name: "Avocado-Ei-Salat", portionen: 2, dauerMin: 15, emoji: "🥑", veggie: true,
    kategorie: "Frühstück", kcal: 360, farbe: "#15803d", saison: ["Sommer"], rating: 4.5, bewertungen: 534, diaet: ["vegetarisch", "keto", "low-carb", "high-protein"],
    beschreibung: "Cremiger Avocado-Salat mit Ei – sättigend und low carb.",
    schritte: ["Eier kochen & vierteln.", "Avocado würfeln.", "Mit Tomate, Öl & Salz mischen."],
    zutaten: [
      { name: "Avocado", menge: 2, einheit: "Stk", kategorie: "gemuese" },
      { name: "Eier", menge: 4, einheit: "Stk", kategorie: "eier" },
      { name: "Tomaten", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "caesar", name: "Hähnchen-Caesar-Salat", portionen: 2, dauerMin: 20, emoji: "🥗", veggie: false,
    kategorie: "Familie", kcal: 440, farbe: "#16a34a", rating: 4.5, bewertungen: 498, diaet: ["low-carb", "high-protein"],
    beschreibung: "Knackiger Caesar-Salat mit gebratenem Hähnchen und Parmesan.",
    schritte: ["Hähnchen würzen & braten.", "Salat mit Dressing mischen.", "Hähnchen & Parmesan darüber."],
    zutaten: [
      { name: "Hähnchenbrust", menge: 400, einheit: "g", kategorie: "fleisch" },
      { name: "Parmesan", menge: 60, einheit: "g", kategorie: "kaese" },
      { name: "Tomaten", menge: 2, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "omelette", name: "Käse-Omelette", portionen: 2, dauerMin: 15, emoji: "🍳", veggie: true,
    kategorie: "Frühstück", kcal: 360, farbe: "#eab308", rating: 4.3, bewertungen: 321, diaet: ["vegetarisch", "keto", "low-carb", "high-protein"],
    beschreibung: "Fluffiges Omelette mit geschmolzenem Käse – in 15 Minuten.",
    schritte: ["Eier mit Milch verquirlen.", "In der Pfanne stocken lassen.", "Käse darüber, einklappen."],
    zutaten: [
      { name: "Eier", menge: 6, einheit: "Stk", kategorie: "eier" },
      { name: "Milch", menge: 100, einheit: "ml", kategorie: "milch" },
      { name: "Käse", menge: 150, einheit: "g", kategorie: "kaese" }]}),

  // --- Sommerlich / saisonal ----------------------------------------------
  rez({ id: "salat", name: "Großer Hirtensalat", portionen: 2, dauerMin: 15, emoji: "🥗", veggie: true,
    kategorie: "Vegetarisch", kcal: 320, farbe: "#16a34a", saison: ["Sommer"], rating: 4.4, bewertungen: 432, diaet: ["vegetarisch", "low-carb"],
    beschreibung: "Frischer Salat mit Tomaten, Gurke und Feta – leicht & sommerlich.",
    schritte: ["Tomaten & Gurke würfeln.", "Feta zerbröseln.", "Mit Olivenöl anmachen."],
    zutaten: [
      { name: "Tomaten", menge: 4, einheit: "Stk", kategorie: "gemuese" },
      { name: "Gurke", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Feta", menge: 200, einheit: "g", kategorie: "kaese" },
      { name: "Olivenöl", menge: 50, einheit: "ml", kategorie: "oel" }]}),
  rez({ id: "caprese", name: "Caprese-Teller", portionen: 2, dauerMin: 10, emoji: "🍅", veggie: true,
    kategorie: "Vegetarisch", kcal: 290, farbe: "#dc2626", saison: ["Sommer"], beliebt: true, rating: 4.6, bewertungen: 521, diaet: ["vegetarisch", "low-carb", "keto"],
    beschreibung: "Italienischer Klassiker aus Tomaten, Mozzarella & Olivenöl.",
    schritte: ["Tomaten & Mozzarella schneiden.", "Abwechselnd anrichten.", "Mit Öl, Salz & Basilikum vollenden."],
    zutaten: [
      { name: "Tomaten", menge: 4, einheit: "Stk", kategorie: "gemuese" },
      { name: "Mozzarella", menge: 250, einheit: "g", kategorie: "kaese" },
      { name: "Olivenöl", menge: 30, einheit: "ml", kategorie: "oel" }]}),
  rez({ id: "tomaten_gurken", name: "Tomaten-Gurken-Salat", portionen: 2, dauerMin: 10, emoji: "🥒", veggie: true,
    kategorie: "Vegetarisch", kcal: 180, farbe: "#22c55e", saison: ["Sommer"], budget: true, rating: 4.3, bewertungen: 198, diaet: ["vegetarisch", "vegan", "low-carb"],
    beschreibung: "Erfrischender, leichter Salat – perfekt als Sommer-Beilage.",
    schritte: ["Tomaten & Gurke schneiden.", "Zwiebel fein hacken.", "Mit Öl & Essig anmachen."],
    zutaten: [
      { name: "Tomaten", menge: 4, einheit: "Stk", kategorie: "gemuese" },
      { name: "Gurke", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Zwiebeln", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
  rez({ id: "melonen_feta", name: "Melonen-Feta-Salat", portionen: 2, dauerMin: 10, emoji: "🍉", veggie: true,
    kategorie: "Vegetarisch", kcal: 260, farbe: "#f43f5e", saison: ["Sommer"], beliebt: true, rating: 4.5, bewertungen: 367, diaet: ["vegetarisch", "low-carb"],
    beschreibung: "Süß-salziger Sommer-Salat aus Wassermelone und Feta.",
    schritte: ["Melone würfeln.", "Feta zerbröseln.", "Mit Minze & Olivenöl anrichten."],
    zutaten: [
      { name: "Wassermelone", menge: 600, einheit: "g", kategorie: "obst" },
      { name: "Feta", menge: 200, einheit: "g", kategorie: "kaese" },
      { name: "Olivenöl", menge: 20, einheit: "ml", kategorie: "oel" }]}),
  rez({ id: "gazpacho", name: "Gazpacho", portionen: 2, dauerMin: 15, emoji: "🍅", veggie: true,
    kategorie: "Vegetarisch", kcal: 160, farbe: "#dc2626", saison: ["Sommer"], rating: 4.2, bewertungen: 156, diaet: ["vegetarisch", "vegan", "low-carb"],
    beschreibung: "Kalte spanische Tomatensuppe – ideal für heiße Tage.",
    schritte: ["Gemüse grob schneiden.", "Mit Öl pürieren.", "Gekühlt servieren."],
    zutaten: [
      { name: "Tomaten", menge: 6, einheit: "Stk", kategorie: "gemuese" },
      { name: "Gurke", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Paprika", menge: 1, einheit: "Stk", kategorie: "gemuese" },
      { name: "Olivenöl", menge: 30, einheit: "ml", kategorie: "oel" }]}),

  // --- Frühstück -----------------------------------------------------------
  rez({ id: "pancakes", name: "Fluffige Pancakes", portionen: 2, dauerMin: 20, emoji: "🥞", veggie: true,
    kategorie: "Frühstück", kcal: 420, farbe: "#d97706", beliebt: true, rating: 4.8, bewertungen: 1876, diaet: ["vegetarisch"],
    beschreibung: "Amerikanische Pancakes – luftig, golden, perfekt fürs Wochenende.",
    schritte: ["Mehl, Eier & Milch verrühren.", "Portionsweise backen.", "Mit Sirup servieren."],
    zutaten: [
      { name: "Mehl", menge: 250, einheit: "g", kategorie: "backen" },
      { name: "Eier", menge: 2, einheit: "Stk", kategorie: "eier" },
      { name: "Milch", menge: 300, einheit: "ml", kategorie: "milch" }]}),
  rez({ id: "porridge", name: "Bananen-Porridge", portionen: 2, dauerMin: 10, emoji: "🥣", veggie: true,
    kategorie: "Frühstück", kcal: 350, farbe: "#a16207", budget: true, rating: 4.5, bewertungen: 643, diaet: ["vegetarisch", "high-protein"],
    beschreibung: "Warmes Haferflocken-Porridge mit Banane – sättigt lange.",
    schritte: ["Haferflocken in Milch aufkochen.", "Banane unterrühren.", "Mit Beeren toppen."],
    zutaten: [
      { name: "Haferflocken", menge: 120, einheit: "g", kategorie: "backen" },
      { name: "Milch", menge: 400, einheit: "ml", kategorie: "milch" },
      { name: "Banane", menge: 2, einheit: "Stk", kategorie: "obst" }]}),
  rez({ id: "quark_beeren", name: "Magerquark mit Beeren", portionen: 1, dauerMin: 5, emoji: "🫐", veggie: true,
    kategorie: "Frühstück", kcal: 240, farbe: "#7c3aed", saison: ["Sommer"], rating: 4.6, bewertungen: 712, diaet: ["vegetarisch", "low-carb", "high-protein"],
    beschreibung: "Proteinreicher Quark mit frischen Beeren – schnell & gesund.",
    schritte: ["Quark glatt rühren.", "Beeren waschen.", "Anrichten & genießen."],
    zutaten: [
      { name: "Magerquark", menge: 250, einheit: "g", kategorie: "milch" },
      { name: "Beeren", menge: 125, einheit: "g", kategorie: "obst" }]}),
  rez({ id: "ruehrei", name: "Rührei mit Brot", portionen: 2, dauerMin: 10, emoji: "🍳", veggie: true,
    kategorie: "Frühstück", kcal: 380, farbe: "#eab308", budget: true, rating: 4.4, bewertungen: 423, diaet: ["vegetarisch", "high-protein", "low-carb"],
    beschreibung: "Klassisches cremiges Rührei mit frischem Brot.",
    schritte: ["Eier verquirlen & würzen.", "In Butter sanft stocken lassen.", "Mit Brot servieren."],
    zutaten: [
      { name: "Eier", menge: 6, einheit: "Stk", kategorie: "eier" },
      { name: "Brot", menge: 4, einheit: "Scheiben", kategorie: "backen" }]}),
  rez({ id: "lachs", name: "Ofenlachs mit Kartoffeln", portionen: 2, dauerMin: 40, emoji: "🐟", veggie: false, schwierigkeit: "mittel",
    kategorie: "Fisch", kcal: 580, farbe: "#0891b2", rating: 4.7, bewertungen: 540, diaet: ["high-protein"],
    beschreibung: "Saftiger Lachs aus dem Ofen mit knusprigen Kartoffeln und Zitrone.",
    schritte: ["Kartoffeln 25 Min backen.", "Lachs mit Zitrone würzen, mitbacken.", "Zusammen servieren."],
    zutaten: [
      { name: "Lachsfilet", menge: 300, einheit: "g", kategorie: "fisch" },
      { name: "Kartoffeln", menge: 600, einheit: "g", kategorie: "gemuese" },
      { name: "Zitrone", menge: 1, einheit: "Stk", kategorie: "gemuese" }]}),
];

// Visuelle Kollektionen oben im Rezeptbuch (key = Filter).
const KOLLEKTIONEN = [
  { key: "Beliebt", titel: "Derzeit beliebt", emoji: "🔥", farbe: "#ef4444" },
  { key: "Saisonal", titel: "Sommerlich & frisch", emoji: "☀️", farbe: "#f59e0b" },
  { key: "Schnell", titel: "In 20 Minuten", emoji: "⚡", farbe: "#10b981" },
  { key: "Vegan", titel: "Vegan", emoji: "🌱", farbe: "#16a34a" },
  { key: "Keto", titel: "Keto & Low Carb", emoji: "🥑", farbe: "#0ea5e9" },
  { key: "HighProtein", titel: "High Protein", emoji: "💪", farbe: "#8b5cf6" },
  { key: "Budget", titel: "Günstig kochen", emoji: "💶", farbe: "#64748b" },
];

// Filter-Chips (key).
const REZEPT_KATEGORIEN = ["Alle", "Beliebt", "Saisonal", "Schnell", "Vegetarisch", "Vegan", "Keto", "LowCarb", "HighProtein", "Klassiker", "Pasta", "Familie", "Fisch", "Frühstück", "Budget"];

// Bild-Stichwörter (englisch) je Rezept für den Foto-CDN. Echte Fotos via LoremFlickr.
const BILDER = {
  bolognese: "spaghetti", carbonara: "carbonara", pasta_pesto: "pesto", nudeln_tomate: "pasta",
  thunfisch_pasta: "tuna", lasagne: "lasagna", kaesespaetzle: "spaetzle", risotto: "risotto",
  gulasch: "goulash", haehnchen: "chickenrice", wraps: "burrito", pizza: "pizza", burger: "cheeseburger",
  haehnchen_bowl: "ricebowl", curry: "curry", chili: "chili", linsen_dal: "dal", kichererbsen_curry: "chickpeas",
  tofu_pfanne: "tofu", gemuesepfanne: "stirfry", kartoffelsuppe: "potatosoup", milchreis: "ricepudding",
  zoodles: "zucchini", steak_brokkoli: "steak", lachs_spinat: "salmon", avocado_ei: "avocado",
  caesar: "caesarsalad", omelette: "omelette", salat: "greeksalad", caprese: "caprese",
  tomaten_gurken: "cucumbersalad", melonen_feta: "watermelon", gazpacho: "gazpacho", pancakes: "pancakes",
  porridge: "porridge", quark_beeren: "berries", ruehrei: "scrambledeggs", lachs: "salmondish",
};

const ANGEBOTE = [
  { id: "a1", markt: "aldi", produktname: "Frisches Hackfleisch gemischt 500g", kategorie: "fleisch", preis: 3.49, normalpreis: 4.49, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a2", markt: "rewe", produktname: "Bio-Hackfleisch Rind 400g", kategorie: "fleisch", preis: 4.99, normalpreis: 5.99, einheit: "400g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a3", markt: "lidl", produktname: "Hähnchenbrustfilet 1kg", kategorie: "fleisch", preis: 6.99, normalpreis: 8.49, einheit: "1kg", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a4", markt: "edeka", produktname: "Bio-Hähnchenbrust 600g", kategorie: "fleisch", preis: 7.49, normalpreis: 8.99, einheit: "600g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a5", markt: "aldi", produktname: "Spaghetti 500g", kategorie: "nudeln", preis: 0.79, normalpreis: 1.09, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a6", markt: "rewe", produktname: "Bio-Spaghetti 500g", kategorie: "nudeln", preis: 1.29, normalpreis: 1.69, einheit: "500g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a7", markt: "lidl", produktname: "Basmatireis 1kg", kategorie: "reis", preis: 1.99, normalpreis: 2.79, einheit: "1kg", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a8", markt: "edeka", produktname: "Bio-Basmatireis 500g", kategorie: "reis", preis: 2.49, normalpreis: 2.99, einheit: "500g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a9", markt: "aldi", produktname: "Zwiebeln 2kg Netz", kategorie: "gemuese", preis: 1.49, normalpreis: 1.99, einheit: "2kg", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a10", markt: "lidl", produktname: "Paprika rot 500g", kategorie: "gemuese", preis: 1.79, normalpreis: 2.49, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a11", markt: "rewe", produktname: "Bio-Paprika Mix 500g", kategorie: "gemuese", preis: 2.49, normalpreis: 2.99, einheit: "500g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a12", markt: "edeka", produktname: "Brokkoli Stück", kategorie: "gemuese", preis: 0.99, normalpreis: 1.49, einheit: "Stk", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a13", markt: "aldi", produktname: "Rispentomaten 500g", kategorie: "gemuese", preis: 1.29, normalpreis: 1.99, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a14", markt: "lidl", produktname: "Salatgurke", kategorie: "gemuese", preis: 0.59, normalpreis: 0.89, einheit: "Stk", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a15", markt: "rewe", produktname: "Knoblauch 200g", kategorie: "gemuese", preis: 0.89, normalpreis: 1.19, einheit: "200g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a16", markt: "aldi", produktname: "Gehackte Tomaten 400g Dose", kategorie: "konserven", preis: 0.49, normalpreis: 0.79, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a17", markt: "edeka", produktname: "Bio-Kokosmilch 400ml", kategorie: "konserven", preis: 1.19, normalpreis: 1.59, einheit: "400ml", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a18", markt: "lidl", produktname: "Kokosmilch 400ml", kategorie: "konserven", preis: 0.89, normalpreis: 1.29, einheit: "400ml", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a19", markt: "rewe", produktname: "Pesto Genovese 190g", kategorie: "konserven", preis: 1.79, normalpreis: 2.29, einheit: "190g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a20", markt: "aldi", produktname: "Frische Vollmilch 3,8% 1L", kategorie: "milch", preis: 0.99, normalpreis: 1.19, einheit: "1L", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a21", markt: "rewe", produktname: "Bio-Vollmilch 3,8% 1L", kategorie: "milch", preis: 1.39, normalpreis: 1.59, einheit: "1L", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a22", markt: "lidl", produktname: "Eier Bodenhaltung 10er", kategorie: "eier", preis: 1.79, normalpreis: 2.29, einheit: "10 Stk", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a23", markt: "edeka", produktname: "Bio-Eier 6er", kategorie: "eier", preis: 2.49, normalpreis: 2.99, einheit: "6 Stk", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a24", markt: "aldi", produktname: "Gouda jung 400g", kategorie: "kaese", preis: 2.99, normalpreis: 3.79, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a25", markt: "rewe", produktname: "Parmigiano Reggiano 150g", kategorie: "kaese", preis: 2.99, normalpreis: 3.49, einheit: "150g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a26", markt: "lidl", produktname: "Feta 200g", kategorie: "kaese", preis: 1.49, normalpreis: 1.99, einheit: "200g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a27", markt: "edeka", produktname: "Olivenöl nativ extra 500ml", kategorie: "oel", preis: 4.99, normalpreis: 6.49, einheit: "500ml", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a28", markt: "rewe", produktname: "Rote Currypaste 195g", kategorie: "gewuerze", preis: 1.99, normalpreis: 2.49, einheit: "195g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a29", markt: "aldi", produktname: "Kidneybohnen 400g Dose", kategorie: "konserven", preis: 0.55, normalpreis: 0.85, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a30", markt: "lidl", produktname: "Mais 300g Dose", kategorie: "konserven", preis: 0.69, normalpreis: 0.99, einheit: "300g", istBio: false, gueltigBis: "2026-06-21" },
  // Neue Angebote für die erweiterte Rezeptauswahl
  { id: "a31", markt: "aldi", produktname: "Zucchini 500g", kategorie: "gemuese", preis: 0.89, normalpreis: 1.29, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a32", markt: "edeka", produktname: "Avocado 2 Stk reif", kategorie: "gemuese", preis: 1.99, normalpreis: 2.79, einheit: "2 Stk", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a33", markt: "lidl", produktname: "Blattspinat TK 600g", kategorie: "gemuese", preis: 1.29, normalpreis: 1.79, einheit: "600g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a34", markt: "rewe", produktname: "Champignons 400g", kategorie: "gemuese", preis: 1.29, normalpreis: 1.79, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a35", markt: "edeka", produktname: "Rinder-Rumpsteak 300g", kategorie: "fleisch", preis: 5.99, normalpreis: 7.99, einheit: "300g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a36", markt: "rewe", produktname: "Rindergulasch 500g", kategorie: "fleisch", preis: 5.49, normalpreis: 6.99, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a37", markt: "rewe", produktname: "Rote Linsen 500g", kategorie: "huelsenfruechte", preis: 1.29, normalpreis: 1.69, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a38", markt: "lidl", produktname: "Kichererbsen 400g Dose", kategorie: "huelsenfruechte", preis: 0.69, normalpreis: 0.99, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a39", markt: "rewe", produktname: "Bio-Tofu natur 400g", kategorie: "tofu", preis: 1.49, normalpreis: 1.99, einheit: "400g", istBio: true, gueltigBis: "2026-06-21" },
  { id: "a40", markt: "aldi", produktname: "Haferflocken zart 500g", kategorie: "backen", preis: 0.59, normalpreis: 0.89, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a41", markt: "aldi", produktname: "Bananen 1kg", kategorie: "obst", preis: 1.19, normalpreis: 1.59, einheit: "1kg", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a42", markt: "lidl", produktname: "Magerquark 500g", kategorie: "milch", preis: 0.69, normalpreis: 0.99, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a43", markt: "edeka", produktname: "Heidelbeeren 125g", kategorie: "obst", preis: 1.99, normalpreis: 2.49, einheit: "125g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a44", markt: "aldi", produktname: "Thunfisch in Wasser 3x80g", kategorie: "konserven", preis: 1.99, normalpreis: 2.79, einheit: "3x80g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a45", markt: "edeka", produktname: "Wassermelone Stück", kategorie: "obst", preis: 2.49, normalpreis: 3.49, einheit: "Stk", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a46", markt: "aldi", produktname: "Mozzarella 125g", kategorie: "kaese", preis: 0.79, normalpreis: 0.99, einheit: "125g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a47", markt: "rewe", produktname: "Frischer Pizzateig 400g", kategorie: "backen", preis: 1.49, normalpreis: 1.99, einheit: "400g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a48", markt: "aldi", produktname: "Bauernbrot 500g", kategorie: "backen", preis: 0.99, normalpreis: 1.29, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a49", markt: "edeka", produktname: "Frische Spätzle 500g", kategorie: "nudeln", preis: 1.29, normalpreis: 1.79, einheit: "500g", istBio: false, gueltigBis: "2026-06-21" },
  { id: "a50", markt: "lidl", produktname: "Kartoffeln festkochend 2kg", kategorie: "gemuese", preis: 1.49, normalpreis: 2.19, einheit: "2kg", istBio: false, gueltigBis: "2026-06-21" },
];

// Prospekte für den KI-Import (Stufe 2).
const PROSPEKTE = [
  { id: "p_penny", markt: "penny", titel: "Penny", zeitraum: "Mo–Sa diese Woche", farbe: "#e2001a", angebote: [
    { id: "p1", markt: "penny", produktname: "Hähnchenbrustfilet 500g", kategorie: "fleisch", preis: 3.33, normalpreis: 4.29, einheit: "500g", istBio: false, gueltigBis: "2026-06-20" },
    { id: "p2", markt: "penny", produktname: "Kartoffeln festkochend 2kg", kategorie: "gemuese", preis: 1.59, normalpreis: 2.29, einheit: "2kg", istBio: false, gueltigBis: "2026-06-20" },
    { id: "p3", markt: "penny", produktname: "Mehl Type 405 1kg", kategorie: "backen", preis: 0.59, normalpreis: 0.89, einheit: "1kg", istBio: false, gueltigBis: "2026-06-20" },
    { id: "p4", markt: "penny", produktname: "Weizentortillas 8 Stk", kategorie: "backen", preis: 1.29, normalpreis: 1.79, einheit: "8 Stk", istBio: false, gueltigBis: "2026-06-20" },
  ]},
  { id: "p_edeka", markt: "edeka", titel: "Edeka", zeitraum: "ganze Woche", farbe: "#005baa", angebote: [
    { id: "p5", markt: "edeka", produktname: "Frischer Lachs Filet 300g", kategorie: "fisch", preis: 4.99, normalpreis: 6.99, einheit: "300g", istBio: false, gueltigBis: "2026-06-21" },
    { id: "p6", markt: "edeka", produktname: "Bio-Zitronen 4 Stk", kategorie: "gemuese", preis: 1.49, normalpreis: 1.99, einheit: "4 Stk", istBio: true, gueltigBis: "2026-06-21" },
    { id: "p7", markt: "edeka", produktname: "Tortilla Wraps 6 Stk", kategorie: "backen", preis: 1.49, normalpreis: 1.99, einheit: "6 Stk", istBio: false, gueltigBis: "2026-06-21" },
  ]},
];

// Stichwörter fürs unscharfe Matching (Platzhalter für KI-Produktabgleich).
const MATCH_STICHWOERTER = {
  "hackfleisch": ["hackfleisch", "hack"],
  "spaghetti": ["spaghetti", "pasta", "nudeln"],
  "spätzle": ["spätzle", "spaetzle"],
  "zwiebeln": ["zwiebel"],
  "tomaten (dose)": ["gehackte tomaten", "tomaten 400", "tomaten 800", "dose"],
  "knoblauch": ["knoblauch"],
  "parmesan": ["parmesan", "parmigiano"],
  "kokosmilch": ["kokosmilch"],
  "paprika": ["paprika"],
  "reis": ["reis", "basmati"],
  "currypaste": ["currypaste", "curry"],
  "hähnchenbrust": ["hähnchenbrust", "hähnchen", "huhn"],
  "brokkoli": ["brokkoli"],
  "eier": ["eier"],
  "milch": ["milch", "vollmilch"],
  "magerquark": ["magerquark", "quark"],
  "käse": ["gouda", "käse", "emmentaler"],
  "tomaten": ["rispentomaten", "tomaten 500", "tomaten"],
  "gurke": ["gurke"],
  "feta": ["feta"],
  "mozzarella": ["mozzarella"],
  "olivenöl": ["olivenöl", "olivenoel"],
  "pesto": ["pesto"],
  "kidneybohnen": ["kidneybohnen", "bohnen"],
  "mais": ["mais"],
  "rote linsen": ["linsen"],
  "kichererbsen": ["kichererbsen"],
  "tofu": ["tofu"],
  "lachsfilet": ["lachs"],
  "kartoffeln": ["kartoffeln", "kartoffel"],
  "zitrone": ["zitrone", "zitronen"],
  "mehl": ["mehl"],
  "haferflocken": ["haferflocken"],
  "tortillas": ["tortilla", "wraps"],
  "speck": ["speck", "bacon", "pancetta"],
  "zucchini": ["zucchini"],
  "avocado": ["avocado"],
  "spinat": ["spinat"],
  "champignons": ["champignons", "pilze"],
  "rindersteak": ["steak", "rumpsteak"],
  "rindergulasch": ["gulasch"],
  "banane": ["banane", "bananen"],
  "beeren": ["heidelbeeren", "beeren"],
  "thunfisch": ["thunfisch"],
  "wassermelone": ["wassermelone", "melone"],
  "pizzateig": ["pizzateig"],
  "brot": ["brot", "baguette"],
};

const WOCHENTAGE = ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"];
const HEUTE_INDEX = 0; // Mo als "heute" für die Demo
